name: Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install && npm install --global jest
      working-directory: ./src/client
    - name: Run tests
      run: npm run test
      working-directory: ./