name: Jest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
      working-directory: ./final-year-project/src/client
    - name: Run tests
      run: npm run test
      working-directory: ./final-year-project/